### ISSUE TITLE
Code in buildlib that needs to be in buildnml

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/WW3_interface#9]
The following code and perhaps more needs to be in the buildnml and not the buildlib.   https://github.com/ESCOMP/WW3_interface/blob/main/cime_config/buildlib#L105
The reason is that for a hybrid or branch run or in a ERR test the buildlib will not be run and therefore file mod_def.ww3 will not be present in the run directory.   The buildlib script is only intended to build the executable, file staging should be done in the buildnml script.

**Comment by jedwards4b** [comment]
@mvertens it looks like you wrote this code in buildlib - can we talk about how we can move it to buildnml or take some other steps so that it will work - it will also fail in cloned cases where you use the --keepexe option.

**Comment by mvertens** [comment]
@jedwards - happy to chat about this.
